public class ParametreliMetotlar11 {
    //Bu method parameter olarak string bir deger alsin. Bu string in karakter sayisini return etsin.
    public void uzunluk(string text){
        text uzn = text.length();
        return uzn();

    }
    //Bu method parametre olarak integer bir deger alsin ve u integer degerin kac rakamdan olustugunu return etsin.
    public integer rakamSayisi(integer number);
          string.valueOf(number);
          string strNum = String.valueOf(number);
          returnstrNum.length();
          integer rkmNum = rkmNum.length();
          return rkmNum;
}
