public class salesforceDeveloper {
        public void myFirstCode() {
            string myFavCity = 'Bodrum';
            System.debug(myFavCity);   

            string myFavMovie = 'Forrest Gump';
            System.debug(myFavMovie);

            string myFavSeason = 'Fall';
            System.debug(myFavSeason);

            System.debug('My  favorite city is ' +myFavCity+', my favorite movie is ' +myFavMovie+ ' and my favorite season is ' +myFavSeason );

            string myCity = 'Washington DC';
            System.debug(myCity);

            integer myFavNumber = 777;
            System.debug(myFavNumber);


    }
}

