public class Primitivedata_Assignment {
    public void printPrimitivedata_Assignment(){
        ID accountId = '001Do000003CYQOIA4';
        string accountName = 'Is this id belongs to Edge Communications?';
        boolean isItHotRating = true;

        system.debug('account id is ' + accountId);
        system.debug('account name => ' + accountName);
        system.debug('is it hot rating? ' + isItHotRating);
        
        }
}
